---------------------------------------------------------------------
-- PRINT_COMP: ERROR
-- Frame: PRINT_FRAME | GameTime: PRINT_GTIME | TickTime: PRINT_TTIME
-- File: 'PRINT_FILE'
-- Message: PRINT_MESSAGE
---------------------------------------------------------------------